### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by Nyomaa** [Gustaf-C/anki-chinese-support-3#22]
Sounds work from Google but only for new cards. I tried to erase, create again the "sound" part and refill it with the addon, it downloads the sounds, fill the sound part but when I play the card, the sound doesn't play. No sound for new or old cards with Baidu

 - OS: Windows 10 Professionnel
 - Anki Version v ⁨2.1.66 
- Chinese Support Version : 3

**Comment by Nyomaa** [comment]
ERRATUM : Even with google, sound doesn't play with all new cards. I have created one, 音乐, it works, 歌手, the file is downloaded but sound doesn't play...

**Comment by Gustaf-C** [comment]
Baidu has changed its API for tts, so it is currently unavailable, I'm investigation wether it can be re-enabled. I'll update the menu for that

As for google:
Are they the same card type?
Have you specified in the card template that a sound should be played?
Are you able to play the mp3 files it downloads in the media folder?

**Comment by Nyomaa** [comment]
Are they the same card type? Yes, I only have 1 card type
Have you specified in the card template that a sound should be played? Yes, it is supposed to be played automatically
Are you able to play the mp3 files it downloads in the media folder? I don't know where is that folder ?

Since the yesterday update, it works ! (with google speech I haven't tried Baidu)

**Comment by Gustaf-C** [comment]
Great to hear that it works!
I haven't touched the google tts code since I first released the addon, so I doubt the last update made a difference :).

The downloaded mp3 files should be in your collection.media folder. The easiest way to find it is to:

- Open the addon list in Anki
- Click view files
- Go up one folder level
- Open your profile folder
- Open collection.media

Check there if you are unable to play any mp3 files (especially those whose audio won't work), if so these are corrupted and need to be removed in order for the addon to re-download them.

**Comment by Gustaf-C** [comment]
I'm closing this as completed since the issue seems to be resolved.
