### ISSUE TITLE
Unable to say if the plugin is active or not

### ISSUE THREAD

**Issue by gdelmee** [Gustaf-C/anki-chinese-support-3#28]
The "汉字" button in the toolbar doesn’t allow to see if the plugin is currently active or not:
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/17324443/aaa765b3-8f4d-4fa2-a60a-49ec9458c322)

This means sometimes it doesn’t trigger anything even we’d like too.

But the annoying part is when having done some changes in Pinyin (to help distinguish homophones) and/or classifiers (to remove traditional ones), those are overwritten if we navigate through Hanzi field, then having to redo those customizations.

Before:
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/17324443/1e145a22-5907-42b3-bcff-41ce0f5cb8b1)

After:
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/17324443/371e2796-b349-4ccf-b7f3-7f3c9cd37888)

**Comment by Gustaf-C** [comment]
I agree that the difference between having clicked the button and not is currently extremely slight and something I'd like to improve, on my system at least there is however a small difference between having clicked the button and not. 

![Screenshot 2023-11-08 at 10 36 40 ](https://github.com/Gustaf-C/anki-chinese-support-3/assets/106698658/f9fabaea-90ef-4a1b-83bb-62f5f8d1e4e3)
![Screenshot 2023-11-08 at 10 36 34 ](https://github.com/Gustaf-C/anki-chinese-support-3/assets/106698658/2e140d5a-6332-4fa9-adea-e22938716d64)

Are you sure that there is actually _no_ difference between the two for you? Because that would indicate that something larger needs fixed.

**Comment by gdelmee** [comment]
Indeed, putting those side-by-side with a good zoom, I can see a light shadow when activated:
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/17324443/864841f8-642b-4e67-ba00-bf2828957d46)

![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/17324443/b420c568-b876-4de6-8fce-0c2d836a4f53)


But nothing I can spot on the fly, really.

**Comment by kieranlblack** [comment]
There was actually an issue where the button was not being correctly toggled when an editor was opened even when it was enabled, have a fix for that in #30. As for the looks of the button, we can modify the css of the button at the same time we react to toggles internally. Maybe green when is enabled and no colour otherwise?

**Comment by Gustaf-C** [comment]
> As for the looks of the button, we can modify the css of the button at the same time we react to toggles internally. Maybe green when is enabled and no colour otherwise?

Yes that is something along what I was thinking, although I was planning to make it blue to fit in more with other UI elements.

**Comment by kieranlblack** [comment]
@Gustaf-C @mdyan @gdelmee Thoughts?

I think I would personally be in favour of making the font not bold here. Also, I think the shifting in the text on the button is due to using text instead of an icon, something I can hammer out in the future but wanted to get initial thoughts.

<img width="581" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/6fb633e4-8810-4e96-91da-d4a4039ebef8">
<img width="596" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/4d73ac53-d95d-475f-8aa7-1cc503abb97c">
<img width="581" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/684a821b-60e1-46e8-89ce-e80553b93b2a">
<img width="580" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/90699ca6-ce4f-47ec-a9ee-5a8e63c35ccb">

**Comment by Gustaf-C** [comment]
Yeah that's a clear improvement, I like it! I agree that not having a bold font would probably look nicer.

A detail though is that I think the colour should match the one used for highlighting the selected field.

**Comment by kieranlblack** [comment]
Using the same colour which is used for highlighting the field might be confusing, since the button itself is not highlighted. Like for example how the Add button is highlighted here
<img width="365" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/f2ee7386-e070-426f-9711-77627274b291">

It looks identical to what an active state would look like for the toggle
<img width="370" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/0a082096-d8d3-4031-a83b-cbf76fc36eaf">

**Comment by Gustaf-C** [comment]
Yeah now that I see it that does look a bit confusing. Maybe turning the entire button blue? I think that was how anki worked a while ago.

But yeah I agree that this is an issue that really affects every toggle-able button in the editor.

**Comment by kieranlblack** [comment]
Without fixing this upstream in Anki itself it is slightly hacky but we can get something like.

![demo](https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/4584d605-a696-49ed-aa38-72642fc8492f)

**Comment by Gustaf-C** [comment]
Fixing it in anki might be the best way to do it, but I think that looks good!

If anki improves it later we can always go back to the default.

**Comment by kieranlblack** [comment]
Perhaps we can do this for now and also make a post on the forum about the issue calling attention to it for dae. While this works for now, it would be ideal to have a more standardized approach, and I'm not sure what that looks like. I'm sure there are accessibility concerns and other complexities I am not aware of.
