### ISSUE TITLE
Bulk add from Hanzi list

### ISSUE THREAD

**Issue by scddo** [Gustaf-C/anki-chinese-support-3#48]
I would like to be able to bulk add entries from a text file list of Hanzi, for which the fields will automatically fill out for every entry. Do people usually manually add each word to their deck? If you have an extensive list, I figure there must be a better way to do this, but I am unsure what other users typically do. 

The solution would best be a menu option to select a text file to grab words from.

Alternatively, I have just been adding words manually with the addon and using the tab key on each hanzi entry to fill out all the fields. I think there must be a better way to do this.

**Comment by Gustaf-C** [comment]
Unless i understand you wrong, you could just import the list of hanzi into a deck and then bulk fill normally?

**Comment by gdelmee** [comment]
As far as I know, there is no bulk import feature in Anki.
Even so, the main issue to solve will be the text analyzer to "cut" the text at the right place, not character per character. Or maybe do you plan to set already one word per line in the text file?

Otherwise, to answer your question, yes, I enter words one by one. In fact, I put in Anki the words I have already learned. Anki is to facilite memorization, not learning directly.
Thankfully, this add-on is a time saver to fill al l the fields.

**Comment by Gustaf-C** [comment]
Since there are already ways to do this I will close this issue.
